USE nutri_mithu2;

-- Set the initial auto-increment value
ALTER TABLE snacks AUTO_INCREMENT = 40001;

INSERT INTO snacks (name, calories_per_serving) VALUES
('1 Cup Tea', 90),
('Munchee Marie Biscuit', 115),
('Maliban Marie Biscuit', 120),
('Munchee Chocolate Biscuit', 100),
('Maliban Chocolate Biscuit', 105),
('Munchee Lemon Puff', 110),
('Maliban Lemon Puff', 120),
('Munchee Ginger Biscuit', 110),
('Maliban Smart Cream Cracker', 100),
('Munchee Milk Short Cake', 130),
('Maliban Gold Marie', 125),
('Munchee Hawaiian Cookies', 140),
('Maliban Nice Biscuit', 150),
('Munchee Chocolate Puff', 125),
('Marshmallow (generic)', 100),
('Munchee Ginger Roll', 120),
('Pebble Sweets (generic)', 130),
('Murukku (generic)', 150),
('Seeni Murukku', 160),
('Coconut Toffee', 120),
('Cadbury Dairy Milk Chocolate', 135),
('Kit Kat (4 finger)', 218),
('Tic Tac Toffees', 110),
('Ferrero Rocher', 150),
('Kithul Jaggery', 130),
('Munchee Milk Toffees', 125),
('Chikki (Peanut Brittle)', 150),
('Cadbury Gems', 140),
('Snickers Bar', 250),
('Sri Lankan Kokis', 110),
('Aluwa (Sri Lankan sweet)', 120),
('Traditional Athirasa', 150),
('Sesame Rolls', 120),
('Bombai Motai', 115),
('Rulang Aluwa', 140),
('Sri Lankan Watalappan', 200),
('Pol Toffee (Coconut Toffee)', 120),
('Munchee Chocolate Cream Biscuit', 140),
('Cadbury Crunchie Bar', 190),
('Kaju Aluwa (Cashew Sweet)', 140),
('Munchee Nice Biscuit', 150),
('Maliban Cheese Puff', 130),
('Elephant House Ice Cream Cup', 160),
('Elephant House Lemonade', 90),
('Coca-Cola (Can)', 140),
('Elephant House Cream Soda', 120),
('Fanta (Can)', 135),
('Pepsi (Can)', 150),
('Ceylon Biscuits Chocolate Chips', 140),
('Ceylon Biscuits Orange Cream', 150),
('Kist Nectar', 110),
('Tipi Tip (Snack)', 160),
('Munchee Milk Short Bread', 130),
('Lays (Chips)', 130),
('Pringles (Original)', 210),
('Oreo Cookies', 160),
('Munchee Chocolate Fingers', 150),
('Maliban Chocolate Puff', 150),
('Munchee Swiss Roll', 190),
('Maliban Swiss Roll', 195),
('Munchee Cracker', 130),
('Elephant House Milk Toffee', 120),
('Elephant House Jelly Cup', 90),
('Munchee Cashew Nut Cookies', 140),
('Ceylon Biscuits Strawberry Cream', 140),
('Nestlé Milo (Drink Pack)', 160),
('Nestlé Nespray Milk', 130),
('Ceylon Biscuits Milk Shortbread', 120),
('Kist Mixed Fruit Nectar', 110),
('MD Pineapple Jam', 90),
('Elephant House Orange Barley', 95),
('Munchee Hawaiian Shortcake', 140),
('Maliban Gold Cracker', 120),
('Kothmale Curd with Honey', 190),
('Elephant House Choc Chip Ice Cream', 180),
('Elephant House Necto', 120),
('Coca-Cola (Pet Bottle)', 210),
('Keells Polos Roll (Packaged)', 200),
('KFC Crispy Fries (Small Pack)', 300),
('Peanut Brittle (Generic)', 150),
('Munchee Milk Wafer', 140),
('Munchee Vanilla Wafer', 130);